image: gitlab-master.nvidia.com/dl/dgx/pytorch:21.12-py3-devel

test:
  tags:
    - docker
  script:
    - nvidia-smi
    - torchrun --nproc_per_node=2  -m pytest --cov-report=term --cov-report=html --cov=megatron/core tests/'
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - coverage
    expire_in: 30 days
    