image: gitlab-master.nvidia.com/dl/dgx/pytorch:21.12-py3-devel

test:
  tags:
    - docker_gpu_enabled
  script:
    - nvidia-smi
    - torchrun --nproc_per_node=2  -m pytest --cov-report=term --cov-report=html --cov=megatron/core tests/
  artifacts:
    paths:
      - coverage
    expire_in: 30 days
    