image: gitlab-master.nvidia.com/dl/dgx/pytorch:21.12-py3-devel

test:
  script:
    - coverage run -m pytest --cov-report term --cov=megatron/core tests/
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    